spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: LibraryUser123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.example.library: INFO


wishlist:
  rate-limiter:
    # fixed | sliding | redis-token-bucket
    strategy: fixed
